import { Geist, Geist_Mono } from 'next/font/google'
import { AuthProvider } from '@/components/AuthContext'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'CultHive',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo_culthive_svg.svg',
  },
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="fr">
        <head>
          <link
            rel="stylesheet"
            href="/tarteaucitron/css/tarteaucitron.min.css"
          />
          {/* Ajouter le script JavaScript de Tarteaucitron */}
          <script
            src="/tarteaucitron/tarteaucitron.min.js"
            async={false} // Charger de façon synchrone
          />
          <link rel="icon" href="/logo_culthive_svg.svg" />
        </head>

        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
