import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CultHive",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_culthive_svg.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="fr">
        <link rel="icon" href="/logo_culthive_svg.svg" />
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
