import { Geist, Geist_Mono } from 'next/font/google'
import { AuthProvider } from '@/components/AuthContext'
import Script from 'next/script'
import TarteConsent from '@/components/TarteConsent'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'CultHive',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo_culthive_svg.svg',
  },
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="fr">
        <head>

          {/* Google Analytics */}
          <Script
            async
            src="https://www.googletagmanager.com/gtag/js?id=G-BTPWGJ6YHV"
          />
          <Script id="google-analytics">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-BTPWGJ6YHV');
            `}
          </Script>

          <link rel="icon" href="/logo_culthive_svg.svg" />
        </head>

        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <TarteConsent />
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
